### The account to run the CFN template on
target_account:
  name: "ixor.ixordocs-dev"
  account_id: "530152727664"
  sts_role: "admin"
  region: "eu-central-1"

domain: ixordocs.be

loadbalancers:
  - name: ALBExt
    scheme: "internet-facing"
    certificate_arn: "arn:aws:acm:eu-central-1:530152727664:certificate/0dc6fb2e-6175-4be7-9758-4d04cc01a052"
  - name: ALBInt
    scheme: "internal"

ecs_cluster:
  keypair: "id_rsa_rik"
  instance_type: "t2.xlarge"
  cluster_size:
    min: 1
    max: 3

# wa only add ListenerRules to 1 Listener
applicationconfig:
#  - name: "doccle-engine"
#    cfn_name: DoccleEngine
#    target: "ecs"
#    ecs:
#      image: "530152727664.dkr.ecr.eu-central-1.amazonaws.com/ixordocs/portal:latest"
#      containerport: 80
#    lb: ALBInt
#    domains:
#      - name: ixordocs.be
#        cfn_name: IxordocsBe
#        priority: 1
#      - name: ixordocs.com
#        cfn_name: IxordocsCom
#        priority: 2
#  - name: "peppol-engine"
#    cfn_name: PeppolEngine
#    lb: ALBInt
#    domains:
#      - name: ixordocs.be
#        cfn_name: IxordocsBe
#        priority: 3
#      - name: ixordocs.com
#        cfn_name: IxordocsCom
#        priority: 4
  - name: "portal"
    cfn_name: Portal
    target: "ecs"
    ecs:
      image: "530152727664.dkr.ecr.eu-central-1.amazonaws.com/ixordocs/portal:v1.1.41-0"
      containerport: 80
      memory: 1024
      cpu: 512
    lb: ALBExt
    domains:
      - name: ixordocs.be
        cfn_name: IxordocsBe
        priority: 5
      - name: ixordocs.com
        cfn_name: IxordocsCom
        priority: 6

ecs_microservices:
  - name: "portal"

referenced_stacks:
  VPCStackName: "VPCForIxordocsDev"
