name: lemo-sandbox-test

referenced_stacks:
  VPCStackName: VPCForCarePlaygroundStack

target_account:
  region: eu-central-1

ecs_cluster:
  keypair: "id_rsa_rik"
  instance_type: "t2.micro"
  cluster_size:
    min: 1
    max: 3
