AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Create DynamoDB tables (aws-cfn-gen version: {{ gittag | default('na') }})

Resources:
{% for table in dynamodb %}
  DDBTable{{ table.table_name | title }}:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: {{ table.table_name }}
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: {{ table.backup | default('false') }}
      AttributeDefinitions:
{%   for att in table.attributes %}
        - AttributeName: "{{ att.attribute_name }}"
          AttributeType: "{{ att.attribute_type }}"
{%   endfor %}
      KeySchema:
{%   for att in table.key_schema %}
        - AttributeName: "{{ att.attribute_name }}"
          KeyType: "{{ att.key_type }}"
{%   endfor %}
{%   if table.billing_mode is defined and table.billing_mode == 'PAY_PER_REQUEST' %}
      BillingMode: PAY_PER_REQUEST
{%   else %}
      ProvisionedThroughput:
{%     if table.provisioned_throughput is defined %}
        ReadCapacityUnits: {{ table.provisioned_throughput.read_capacity_units | default('5') }}
        WriteCapacityUnits: {{ table.provisioned_throughput.write_capacity_units | default('5') }}
{%     else %}
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
{%     endif %}
{%   endif %}
{%   if table.local_secondary_indexes is defined %}
      LocalSecondaryIndexes:
{%     for lsi in table.local_secondary_indexes %}
        - IndexName: "{{ lsi.index_name }}"
          KeySchema:
{%       for key in lsi.key_schema %}
            - AttributeName: "{{ key.attribute_name }}"
              KeyType: "{{ key.key_type }}"
{%       endfor %}
          Projection:
            ProjectionType: "{{ lsi.projection.projection_type }}"
{%     endfor %}
{%   endif %}
      Tags:
        - Key: Application
          Value: "{{ application }}"
        - Key: Environment
          Value: "{{ env }}"
        - Key: Customer
          Value: "{{ customer | default('NA') }}"
{% endfor %}
