AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Create Hosted Zones (aws-cfn-gen version: {{ gittag | default('na') }})

Resources:

{% if route53 is defined and route53.private_hosted_zones is defined %}
{%   for hosted_zone in route53.private_hosted_zones %}
  Route53PrivateHostedZone{{ hosted_zone.cfn_name }}:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: {{ hosted_zone.name }}
      VPCs:
        -
          VPCId: "{{ vpc_id }}"
          VPCRegion: !Ref 'AWS::Region'
      HostedZoneConfig:
        Comment: "Private hosted zone {{ hosted_zone.name }}"
{%     if hosted_zone.apex_alias is defined %}
  Route53Recordset{{ hosted_zone.cfn_name }}ApexAlias:
    DependsOn: Route53PrivateHostedZone{{ hosted_zone.cfn_name }}
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: "{{ hosted_zone.name | regex_replace('\.$', '') }}."
      Comment: "Apex Alias for {{ hosted_zone.name }}"
      RecordSets:
        - Name: "{{ hosted_zone.name }}"
          Type: A
          AliasTarget:
            HostedZoneId: !ImportValue "{{ cfn_project }}LB{{ hosted_zone.apex_alias }}-{{ hosted_zone.apex_alias }}CanonicalHostedZoneID"
            DNSName:  !ImportValue "{{ cfn_project }}LB{{ hosted_zone.apex_alias }}-{{ hosted_zone.apex_alias }}DNS"
{%     endif %}
{%   endfor %}
{% endif %}

Outputs:
{% if route53 is defined and route53.private_hosted_zones is defined %}
{%   for hosted_zone in route53.private_hosted_zones %}
  Route53PrivateHostedZone{{ hosted_zone.cfn_name }}:
    Value: !Ref "Route53PrivateHostedZone{{ hosted_zone.cfn_name }}"
    Description: "Private hosted zone {{ hosted_zone.name }}"
    Export:
      Name: !Sub "${AWS::StackName}-Route53PrivateHostedZone{{ hosted_zone.cfn_name }}"
{%   endfor %}
{% endif %}
