AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Create Secrets (without a secret, for now) (aws-cfn-gen version: {{ gittag | default('na') }})

Resources:

{% for secret in secrets_manager.secrets %}
  Secret{{ secret.cfn_name }}:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "{{ secret.description | default(secret.cfn_name) }}"
      KmsKeyId: !ImportValue "{{ secret.kms_key_id_import }}"
      Name: "{{ secret.name }}"

  SecretPolicy{{ secret.cfn_name }}:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref Secret{{ secret.cfn_name }}
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
{%   for principal in secret.policy.principals %}
                - {{ principal.principal_string }}
{%   endfor %}
            Action: secretsmanager:GetSecretValue
            Resource: "*"
            Condition:
              ForAnyValue:StringEquals:
                secretsmanager:VersionStage: AWSCURRENT
{% endfor %}
